// P10-BR3 — the test-only secure venue. Support only: it declares ZERO cases.
//
// WHY A TERMINATOR EXISTS AT ALL
// `__Host-` and `Secure` cookie semantics are properties of a secure origin. A
// browser will not honour them over a plain-HTTP origin, and leaning on Chrome's
// localhost exception to pretend otherwise would be testing a weakened version
// of the very rule under observation. The committed repository ships no HTTPS
// topology, and neither the production server entrypoint nor the committed Vite
// configuration exposes one — both are outside this gate's writable ceiling. So
// the secure origin is built here, in test-only code, and nothing about the
// production server or client changes to accommodate it.
//
// WHAT IT IS
// A transport-level TLS front. It terminates HTTPS and forwards bytes onward:
//   /api/*  -> prefix stripped -> the secure-configured production server
//   else    -> the committed Vite dev server
// That is precisely the shape of the committed Vite `/api` proxy, moved in front
// of it because the browser must see one https origin.
//
// WHAT IT IS NOT
// It answers no request of its own, fabricates no response, invents no header,
// rewrites no cookie, and makes no authorization decision. Every status, body,
// and `Set-Cookie` the browser receives was produced by the production server.
// If this file decided anything, the observation would be worthless.
import { spawnSync } from 'node:child_process';
import { createServer as createHttpsServer, type Server } from 'node:https';
import { request as httpRequest, type IncomingMessage, type ServerResponse } from 'node:http';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CLIENT_ORIGIN, SECURE_PORT, SECURE_SERVER_PORT } from './origins.ts';

const VITE_HOST = '127.0.0.1';
const VITE_PORT = 5173;
/** Vite is reached over the loopback address but told the host name it serves
 *  under, so its own host checking sees the origin the browser actually used. */
const VITE_HOST_HEADER = CLIENT_ORIGIN.replace(/^https?:\/\//, '');

export interface Certificate {
  readonly key: Buffer;
  readonly cert: Buffer;
}

/** A short-lived self-signed certificate for `localhost`, generated by the host
 *  OpenSSL. No repository dependency is added: this is host tooling, in the same
 *  class as the `npm`, `node`, and Docker binaries the committed apparatus
 *  already invokes. The browser is launched with certificate errors ignored,
 *  which changes nothing about cookie rules — `Secure` and `__Host-` turn on the
 *  https scheme, not on who signed the certificate. */
export function generateCertificate(): Certificate {
  const dir = mkdtempSync(join(tmpdir(), 'selves-p10-br3-tls-'));
  const keyPath = join(dir, 'key.pem');
  const certPath = join(dir, 'cert.pem');
  const result = spawnSync(
    'openssl',
    [
      'req', '-x509', '-newkey', 'rsa:2048', '-nodes',
      '-keyout', keyPath,
      '-out', certPath,
      '-days', '1',
      '-subj', '/CN=localhost',
      '-addext', 'subjectAltName=DNS:localhost,IP:127.0.0.1',
    ],
    { stdio: ['ignore', 'ignore', 'pipe'] },
  );
  if (result.status !== 0) {
    throw new Error(
      `openssl could not generate the secure-venue certificate: ${String(result.stderr)}`,
    );
  }
  return { key: readFileSync(keyPath), cert: readFileSync(certPath) };
}

/** Forward one request onward and stream the answer back untouched. */
function forward(
  req: IncomingMessage,
  res: ServerResponse,
  port: number,
  path: string,
  hostHeader: string,
): void {
  const headers = { ...req.headers, host: hostHeader };
  // The terminator speaks HTTP/1.1 onward; hop-by-hop fields do not travel.
  delete headers['connection'];
  delete headers['upgrade'];
  const upstream = httpRequest(
    { host: '127.0.0.1', port, method: req.method, path, headers },
    (answer) => {
      // Status and every response header exactly as the upstream produced them,
      // `Set-Cookie` included and unmodified.
      res.writeHead(answer.statusCode ?? 502, answer.headers);
      answer.pipe(res);
    },
  );
  upstream.on('error', () => {
    if (!res.headersSent) res.writeHead(502);
    res.end();
  });
  req.pipe(upstream);
}

export function startSecureVenue(cert: Certificate): Server {
  const server = createHttpsServer({ key: cert.key, cert: cert.cert }, (req, res) => {
    const path = req.url ?? '/';
    if (path === '/api' || path.startsWith('/api/')) {
      // The same prefix strip the committed Vite proxy performs, so the
      // production server sees the paths it actually serves.
      forward(req, res, SECURE_SERVER_PORT, path.replace(/^\/api/, '') || '/', `127.0.0.1:${SECURE_SERVER_PORT}`);
      return;
    }
    forward(req, res, VITE_PORT, path, VITE_HOST_HEADER);
  });
  server.listen(SECURE_PORT, VITE_HOST);
  return server;
}
